import Foundation
import LeapSDK

/// Protocol that types can conform to for structured generation.
/// Use the @Generatable macro to auto-generate conformance.
public protocol GeneratableType: Codable {
  /// Human-readable description of what this type represents
  static var typeDescription: String { get }

  /// JSON schema for this type (generated by @Generatable macro)
  static func jsonSchema() -> String
}

/// Utility for accessing JSON schemas from GeneratableType conforming types
public enum JSONSchemaGenerator {
  /// Get JSON schema for a GeneratableType conforming type
  public static func getJSONSchema<T: GeneratableType>(for type: T.Type) -> String {
    return type.jsonSchema()
  }
}

extension GenerationOptions {
  /// Sets the response format to use the specified GeneratableType's JSON schema
  public func setResponseFormat<T: GeneratableType>(type: T.Type) {
    self.jsonSchemaConstraint = JSONSchemaGenerator.getJSONSchema(for: type)
  }
}
