name: LeapChatExample
options:
  bundleIdPrefix: ai.liquid.examples
  createIntermediateGroups: true
  defaultConfig: Debug
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

configs:
  Debug: debug
  Release: release

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

packages:
  LeapSDK:
    path: ..

targets:
  LeapChatExample:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: LeapChatExample
        name: Sources
        createIntermediateGroups: true
        excludes:
          - "Resources/**"
    resources:
      - path: LeapChatExample/Assets.xcassets
        name: Assets
      - path: LeapChatExample/Resources
        name: Resources
        createIntermediateGroups: true
    dependencies:
      - package: LeapSDK
        product: LeapSDK
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.liquid.LeapChatExample
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        LIBRARY_SEARCH_PATHS: "$(inherited) $(BUILT_PRODUCTS_DIR)/LeapSDK.framework/Frameworks"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/Frameworks/LeapSDK.framework/Frameworks"
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
    postBuildScripts:
      - name: Sign nested LeapSDK dylibs
        script: |
          set -e
          NESTED="${BUILT_PRODUCTS_DIR}/${CONTENTS_FOLDER_PATH}/Frameworks/LeapSDK.framework/Frameworks"
          [ -d "$NESTED" ] || exit 0
          [ "$CODE_SIGNING_ALLOWED" = "YES" ] || exit 0
          find "$NESTED" -name "*.dylib" | while read dylib; do
            codesign --force --sign "$EXPANDED_CODE_SIGN_IDENTITY" --timestamp=none "$dylib"
          done

  LeapChatExampleTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LeapChatExampleTests
    dependencies:
      - target: LeapChatExample
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.liquid.examples.LeapChatExampleTests
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"

  LeapChatExampleUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: LeapChatExampleUITests
    dependencies:
      - target: LeapChatExample
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.liquid.examples.LeapChatExampleUITests
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
