name: LeapChatExample
options:
  bundleIdPrefix: ai.liquid.examples
  createIntermediateGroups: true
  defaultConfig: Debug
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

configs:
  Debug: debug
  Release: release

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

packages:
  LeapSDK:
    url: https://github.com/liquid4all/leap-ios
    from: 0.7.0

targets:
  LeapChatExample:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: LeapChatExample
        name: Sources
        createIntermediateGroups: true
        excludes:
          - "Resources/**"
    resources:
      - path: LeapChatExample/Assets.xcassets
        name: Assets
      - path: LeapChatExample/Resources
        name: Resources
        createIntermediateGroups: true
    dependencies:
      - package: LeapSDK
        product: LeapSDK
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.liquid.examples.LeapChatExample
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_COMPILATION_MODE: wholemodule

  LeapChatExampleTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LeapChatExampleTests
    dependencies:
      - target: LeapChatExample
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.liquid.examples.LeapChatExampleTests
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"

  LeapChatExampleUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: LeapChatExampleUITests
    dependencies:
      - target: LeapChatExample
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.liquid.examples.LeapChatExampleUITests
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
