name: LeapSloganExample
options:
  bundleIdPrefix: ai.liquid.examples
  createIntermediateGroups: true
  defaultConfig: Debug
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

configs:
  Debug: debug
  Release: release

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

packages:
  LeapSDK:
    path: ..

targets:
  LeapSloganExample:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: LeapSloganExample
        excludes:
          - "Resources/**"
    dependencies:
      - package: LeapSDK
        product: LeapSDK
      - package: LeapSDK
        product: LeapSDKMacros
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.liquid.LeapSloganExample
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations~ipad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_VERSION: "5.9"
        DEVELOPMENT_ASSET_PATHS: "\"LeapSloganExample/Preview Content\""
        ENABLE_PREVIEWS: YES
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        LIBRARY_SEARCH_PATHS: "$(inherited) $(BUILT_PRODUCTS_DIR)/LeapSDK.framework/Frameworks"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/Frameworks/LeapSDK.framework/Frameworks"
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
    postBuildScripts:
      - name: Sign nested LeapSDK dylibs
        script: |
          set -e
          NESTED="${BUILT_PRODUCTS_DIR}/${CONTENTS_FOLDER_PATH}/Frameworks/LeapSDK.framework/Frameworks"
          [ -d "$NESTED" ] || exit 0
          [ "$CODE_SIGNING_ALLOWED" = "YES" ] || exit 0
          find "$NESTED" -name "*.dylib" | while read dylib; do
            codesign --force --sign "$EXPANDED_CODE_SIGN_IDENTITY" --timestamp=none "$dylib"
          done
