name: LeapAudioDemo
options:
  bundleIdPrefix: ai.liquid.examples
  createIntermediateGroups: true
  defaultConfig: Debug
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en

configs:
  Debug: debug
  Release: release

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

packages:
  LeapSDK:
    url: https://github.com/liquid4all/leap-ios
    from: 0.7.0

targets:
  LeapAudioDemo:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: LeapAudioDemo
        excludes:
          - "Resources/**"
    resources:
      - path: LeapAudioDemo/Assets.xcassets
        name: Assets
      - path: LeapAudioDemo/Resources
        name: Resources
        createIntermediateGroups: true
    dependencies:
      - package: LeapSDK
        product: LeapSDK
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.liquid.examples.LeapAudioDemo
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        INFOPLIST_KEY_UISupportedInterfaceOrientations~ipad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Audio input is used to capture prompts."
        INFOPLIST_KEY_UIBackgroundModes: "audio"
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_VERSION: "5.9"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
