name: RecipeGenerator
options:
  bundleIdPrefix: ai.liquid
packages:
  LeapSDK:
    path: ..
targets:
  RecipeGenerator:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 18.0
    info:
      path: RecipeGenerator/Info.plist
    sources: [RecipeGenerator, Resources]
    dependencies:
      - package: LeapSDK
        product: LeapSDK
    settings:
      base:

