name: Android LeapChat Build
on: 
  push:
    branches: [ main ]
    paths:
      - 'Android/LeapChat/**'
      - '.github/workflows/android-leap-chat-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Android/LeapChat/**'
      - '.github/workflows/android-leap-chat-build.yml'
  workflow_dispatch:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build Leap Chat
      run: cd Android/LeapChat && ./gradlew :app:assemble
